"""
Django settings for Shopping_website project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_l*rm_$3mp0_uito-525gy&t19ji#j5l8eq#&9-9l#i_luezf-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'ckeditor',
    'ckeditor_uploader',
    'AutoTag',
    'shopping_cart',
    'User',
    'djcelery',
    'CeleryTask',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Shopping_website.middleware.UrlMiddleWare'
]

ROOT_URLCONF = 'Shopping_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Shopping_website.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'static')

CKEDITOR_UPLOAD_PATH = "static/upload"
CKEDITOR_IMAGE_BACKEND = "pillow"

alipay_public_key = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArye9AhzRw1zSwwZ+4c0cD9Cg82lSJBRPHyvvBGwFsnJ/TJOjo4zQOpHTz0/d3IfpMCvQI4JIw93ws1v+bJWgB/XDgiwjIpT8pqFVlvLPVTXNlmBdpFNXtMFlai5DHIKogfuBmswH6v/ZcpVprB7DHAvUmhkTjpemdHs1eWceXfHadM+L1EbrqjpSduyRwRA1pPCqKjnoe4H5pk2jQZL+uOQss3G7FzN56tpXaNSEFmKBgNPu4TXbMt3QjxkS3Rl9b2nOOW1EcoO38G/cfxCSWnqJEIaIPYNPCS6f7xoABLxlX+PF54aLPoyNWIj6bnfuJhkwzXeAx6fliE9QI7aoLQIDAQAB
-----END PUBLIC KEY-----"""

alipay_private_key = """-----BEGIN RSA PRIVATE KEY-----
MIIEogIBAAKCAQEArye9AhzRw1zSwwZ+4c0cD9Cg82lSJBRPHyvvBGwFsnJ/TJOjo4zQOpHTz0/d3IfpMCvQI4JIw93ws1v+bJWgB/XDgiwjIpT8pqFVlvLPVTXNlmBdpFNXtMFlai5DHIKogfuBmswH6v/ZcpVprB7DHAvUmhkTjpemdHs1eWceXfHadM+L1EbrqjpSduyRwRA1pPCqKjnoe4H5pk2jQZL+uOQss3G7FzN56tpXaNSEFmKBgNPu4TXbMt3QjxkS3Rl9b2nOOW1EcoO38G/cfxCSWnqJEIaIPYNPCS6f7xoABLxlX+PF54aLPoyNWIj6bnfuJhkwzXeAx6fliE9QI7aoLQIDAQABAoIBAEfD3GlVLY0CJ0jJDIuv4mOIc6nH6WPm/lQjSBdjuyHWT9osU8vbEiYtQb+bVafZ9+1IxksGQpIeCVUzyBbtZ1hblfNr6iltKeeMCumCKvkaxlVqvnNpwnHJG6hZtB2mWyyGxB+MoWHj2lBcb6OaJw8CueU5iQ3PjOAE63AGlCahFsWL5yxr82qSx0FIVT++4jd/rva71CmhPCFvue/6uOnZm9gzBq/CJ2i7GpWglmTfxXb3joS2FVVuReEh98PPtvWR0FEW2KA27GNKDCnTSYfCM8h9iusELOxGuNrlRzgyo+yHlKXLugy5UJUykit6IIR4eCRPjWlYIe0vSnrfKPECgYEA7nHBfj2XXvTpnprhD+5A446h5zLmguEGAqeMce9NhnVufcolvwjQ7m3m7G8ddQW5yOu6QrZBTtENYvr+mb81NYgu6t2Vl07MdtDGsvLKpL+9HXdgkREoxayR7qo9upKeiGo9oOjtp194RIrYOQLb7jhXIS329wjn30MoKMFlRwMCgYEAvA0Y1qIO7T3ukFr2R6q6jnhfZzC6+2I4ytj22sIAIcSZSP9ZfrfZRFbA+Mra589teaI1fzRBJFrDUPHg9QATPJphdnStI7XG7A/F/18z70DbvfGvXxXwXpHtmqO4SjLVQMRE2dsDhFbKexRc05dY65290nw67OMxQQ/KX+rm1Q8CgYBZzua+EZyt2zkSz+rtASPXkaVRW06PBQoqfcjcMPHWLuzK3BSTe1KWOza63q8NoHZ1QrQI5HR8pyiPm1HBvs7ftsdVFth9AOTp64Crbd79ZmpoasooWXot2e2tItnVJ9wmLT3BGXpJjB/UUSdXccg8VWQbzyAxs10CLl013IG02QKBgBSwNC1Ywt+i0p4bA8E6rS+DWquVltyVH75hRDco5K7SXDLFtOjV/RchnDVCy/Z4wYiCKfSGoSwIuDgthBwwF+2w5kwL5ghptSq/SX8g0CvgLMymzC5f0YP19ffvTxUKpp9reE+nYqmqirgjs1qr6eJyBjIj7K+nBwIrZI5M33xNAoGAV69MTdHtCfpiyULIkCnATEDc/v8Nw+MmzyZmnQ59rrjVYX4XYP84UWZA6VsNi155FLKI6Iavagz1XdUqliRsEmXzxHf0tYheaklHG3guO+q4r+ydwn4rLPDpnAlC6XRzpdqaKdUB2olfssgZkkt48ofZueLanmn878K/DVLnO/Q=
-----END RSA PRIVATE KEY-----"""

appid = "2016100100640637"

import djcelery
djcelery.setup_loader()

BROKER_URL = "redis://127.0.0.1:6379/1"
CELERY_IMPORT = ("CeleryTask.tasks")
CELERY_TIMEZONE = "Asia/Shanghai"
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'

from celery.schedules import timedelta

CELERYBEAT_SCHEDULE = {
    u"测试定时任务": {
        "task": "CeleryTask.tasks.add_v1",
        "schedule": timedelta(seconds=1)
    }
}
